# Generated by Django 4.1.9 on 2023-07-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_libs', '0002_rename_text_madlib_story_madlib_word_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madlib',
            name='words',
        ),
        migrations.AddField(
            model_name='madlib',
            name='num_prompts',
            field=models.IntegerField(default=0),
        ),
    ]
